name: JavaFX Arkanoid CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t arkanoid .

      - name: Run Docker Image and Test
        run: docker run --name builder arkanoid

      - name: Copy target folder
        if: always()
        run: docker cp builder:/app/target .

      - name: Upload Build Product
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-jar
          path: target/*.jar

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-jar
          path: target/*.jar

  release:
    needs: [build-linux, build-windows]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Files
        uses: actions/download-artifact@v4
        with:
          name: linux-build-jar
          path: linux-build

      - name: Download Windows Files
        uses: actions/download-artifact@v4
        with:
          name: windows-build-jar
          path: windows-build

      - name: Copy To Final
        run: |
          mkdir -p final_assets
          find linux-build/ -name "*.jar" ! -name "original-*" -exec cp {} final_assets/Arkanoid-Linux.jar \;
          find windows-build/ -name "*.jar" ! -name "original-*" -exec cp {} final_assets/Arkanoid-Windows.jar \;

      - name: Upload to Github Releases
        uses: softprops/action-gh-release@v2
        with:
          files: final_assets/*
          name: "Arkanoid Release ${{ github.ref_name }}"
          body: |
            Official release version: ${{ github.ref_name }} 
            Run by: java -jar <file_name>.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}